#Copyright (C) 2018 Fernando Porrino Serrano.
#This software it's under the terms of the GNU Affero General Public License version 3.
#Please, refer to (https://github.com/FherStk/DocumentPlagiarismChecker/blob/master/LICENSE) for further licensing details.

global:
  #folder: 'C:\test\M10DAM-LL6'
  #folder: 'C:\test\'
  folder: '/home/porrino.fernando/Documents/Proves'
  #sample: 'C:\test\M10DAM-LL6\Enunciat.pdf'
  #sample: 'C:\test\Sample.pdf'
  sample: '/home/porrino.fernando/Documents/Proves/Sample.pdf'
  extension: 'pdf'
  display: 'comparator'
  #recursive: true
  recursive: false

threshold:
  basic: 0.5
  comparator: 0.5
  details: 0.5
  full: 0